# Generated by Django 4.2.8 on 2023-12-27 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorname", models.CharField(max_length=50)),
                ("authordob", models.DateField()),
                ("authorgender", models.CharField(max_length=20)),
                ("authoremail", models.CharField(max_length=50)),
                ("authorphone", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryname", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cityname", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookname", models.CharField(max_length=50)),
                ("bookdescription", models.CharField(max_length=500)),
                ("bookpublishedon", models.DateField()),
                (
                    "bookprice",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
                ),
                (
                    "bookauthor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookstore.author",
                    ),
                ),
                (
                    "bookcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookstore.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="authorcity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookstore.city"
            ),
        ),
    ]
